
version: "3.7"
services:

  db:
    image: mysql:latest
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mbshop
      MYSQL_USER: mbshop
      MYSQL_PASSWORD: himitu
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/sqls:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
